version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: keyshell-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # Backend Service
  backend:
    build:
      context: ./backend
    container_name: keyshell-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/keyshell
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: keyshell-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis for Caching
  redis:
    image: redis:latest
    container_name: keyshell-redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
