services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - payment-service

  # Auth Service
  auth-service:
    build: ./backend/auth_service
    container_name: auth-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment_app
      - JWT_SECRET=secret-key
    volumes:
      - ./backend/common:/app/common
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - app-network

  # Payment Service
  payment-service:
    build: ./backend/payment_service
    container_name: payment-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment_app
      - ELASTICSEARCH_HOST=elasticsearch
    volumes:
      - ./backend/common:/app/common
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mongodb
      - elasticsearch
      - redis
    networks:
      - app-network

  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Redis for Caching
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb_data:
