services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5044"  # Logstash service address

  auth-service:
    build:
      context: ./backend/auth_service
    environment:
      MONGODB_URI: mongodb://mongodb:27017/payment_app
    volumes:
      - ./backend/common:/app/common
    depends_on:
      - mongodb
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5044"  

  payment-service:
    build:
      context: ./backend/payment_service
    environment:
      MONGODB_URI: mongodb://mongodb:27017/payment_app
    volumes:
      - ./backend/common:/app/common
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5044"  

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - auth-service
      - payment-service
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5044"  

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - payment-service
      - frontend
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5044"  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:5044"  

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
