version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # Adjusted memory allocation (increase if needed)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"  # Elasticsearch HTTP port
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk
    restart: always  # Automatically restart on failure


  logstash:
    build:
      context: ./logstash
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"  # Corrected environment variable for Logstash JVM heap size
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"  # Logstash for Beats
      - "9600:9600"  # Logstash HTTP API
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: always  # Automatically restart on failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "8888:5601"  # Kibana on port 8888
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: always  # Automatically restart on failure

volumes:
  es_data:

networks:
  elk:
    driver: bridge
