global:
  scrape_interval: 15s  # Default scrape interval for scraping targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8000']  

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:4200']  

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']  
